openaiProvider:
  key: ""
  model: "gpt-5.2"
  baseURL: ""
server:
  port: "8077"
napcat:
  apiBaseURL: "http://localhost:3000"
  expectedToken: ""
  authToken: ""
judgeAt:
  enable: true
prompts:
  system: ""